-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.2 (win64) Build 6299465 Fri Nov 14 19:35:11 GMT 2025
-- Date        : Mon Dec  8 18:20:22 2025
-- Host        : Dragon3 running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub
--               c:/Xilinx/MyXilinxProjects/CPUDrivenGPUTest4/CPUDrivenGPUTest4.gen/sources_1/bd/MainDesign/ip/MainDesign_GPRQuad2_0_0/MainDesign_GPRQuad2_0_0_stub.vhdl
-- Design      : MainDesign_GPRQuad2_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcku5p-ffvb676-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity MainDesign_GPRQuad2_0_0 is
  Port ( 
    clk : in STD_LOGIC;
    readQuadIndex : in STD_LOGIC_VECTOR ( 1 downto 0 );
    writeQuadIndex : in STD_LOGIC_VECTOR ( 1 downto 0 );
    portA_en : in STD_LOGIC;
    portA_regType : in STD_LOGIC_VECTOR ( 1 downto 0 );
    portA_regIdx : in STD_LOGIC_VECTOR ( 2 downto 0 );
    portA_regChan : in STD_LOGIC_VECTOR ( 1 downto 0 );
    portA_readOutData : out STD_LOGIC_VECTOR ( 127 downto 0 );
    portB_en : in STD_LOGIC;
    portB_regType : in STD_LOGIC_VECTOR ( 1 downto 0 );
    portB_regIdx : in STD_LOGIC_VECTOR ( 2 downto 0 );
    portB_regChan : in STD_LOGIC_VECTOR ( 1 downto 0 );
    portB_readOutData : out STD_LOGIC_VECTOR ( 127 downto 0 );
    portW_en : in STD_LOGIC;
    portW_regType : in STD_LOGIC_VECTOR ( 1 downto 0 );
    portW_regIdx : in STD_LOGIC_VECTOR ( 2 downto 0 );
    portW_regChan : in STD_LOGIC_VECTOR ( 1 downto 0 );
    portW_writeInData : in STD_LOGIC_VECTOR ( 127 downto 0 );
    clka_bram0 : out STD_LOGIC;
    addra_bram0 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    dina_bram0 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ena_bram0 : out STD_LOGIC;
    wea_bram0 : out STD_LOGIC_VECTOR ( 0 to 0 );
    clkb_bram0 : out STD_LOGIC;
    addrb_bram0 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    enb_bram0 : out STD_LOGIC;
    doutb_bram0 : in STD_LOGIC_VECTOR ( 31 downto 0 );
    clka_bram1 : out STD_LOGIC;
    addra_bram1 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    dina_bram1 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ena_bram1 : out STD_LOGIC;
    wea_bram1 : out STD_LOGIC_VECTOR ( 0 to 0 );
    clkb_bram1 : out STD_LOGIC;
    addrb_bram1 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    enb_bram1 : out STD_LOGIC;
    doutb_bram1 : in STD_LOGIC_VECTOR ( 31 downto 0 );
    clka_bram2 : out STD_LOGIC;
    addra_bram2 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    dina_bram2 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ena_bram2 : out STD_LOGIC;
    wea_bram2 : out STD_LOGIC_VECTOR ( 0 to 0 );
    clkb_bram2 : out STD_LOGIC;
    addrb_bram2 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    enb_bram2 : out STD_LOGIC;
    doutb_bram2 : in STD_LOGIC_VECTOR ( 31 downto 0 );
    clka_bram3 : out STD_LOGIC;
    addra_bram3 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    dina_bram3 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ena_bram3 : out STD_LOGIC;
    wea_bram3 : out STD_LOGIC_VECTOR ( 0 to 0 );
    clkb_bram3 : out STD_LOGIC;
    addrb_bram3 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    enb_bram3 : out STD_LOGIC;
    doutb_bram3 : in STD_LOGIC_VECTOR ( 31 downto 0 );
    clka_bram4 : out STD_LOGIC;
    addra_bram4 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    dina_bram4 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ena_bram4 : out STD_LOGIC;
    wea_bram4 : out STD_LOGIC_VECTOR ( 0 to 0 );
    clkb_bram4 : out STD_LOGIC;
    addrb_bram4 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    enb_bram4 : out STD_LOGIC;
    doutb_bram4 : in STD_LOGIC_VECTOR ( 31 downto 0 );
    clka_bram5 : out STD_LOGIC;
    addra_bram5 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    dina_bram5 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ena_bram5 : out STD_LOGIC;
    wea_bram5 : out STD_LOGIC_VECTOR ( 0 to 0 );
    clkb_bram5 : out STD_LOGIC;
    addrb_bram5 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    enb_bram5 : out STD_LOGIC;
    doutb_bram5 : in STD_LOGIC_VECTOR ( 31 downto 0 );
    clka_bram6 : out STD_LOGIC;
    addra_bram6 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    dina_bram6 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ena_bram6 : out STD_LOGIC;
    wea_bram6 : out STD_LOGIC_VECTOR ( 0 to 0 );
    clkb_bram6 : out STD_LOGIC;
    addrb_bram6 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    enb_bram6 : out STD_LOGIC;
    doutb_bram6 : in STD_LOGIC_VECTOR ( 31 downto 0 );
    clka_bram7 : out STD_LOGIC;
    addra_bram7 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    dina_bram7 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ena_bram7 : out STD_LOGIC;
    wea_bram7 : out STD_LOGIC_VECTOR ( 0 to 0 );
    clkb_bram7 : out STD_LOGIC;
    addrb_bram7 : out STD_LOGIC_VECTOR ( 8 downto 0 );
    enb_bram7 : out STD_LOGIC;
    doutb_bram7 : in STD_LOGIC_VECTOR ( 31 downto 0 )
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of MainDesign_GPRQuad2_0_0 : entity is "MainDesign_GPRQuad2_0_0,GPRQuad2,{}";
  attribute core_generation_info : string;
  attribute core_generation_info of MainDesign_GPRQuad2_0_0 : entity is "MainDesign_GPRQuad2_0_0,GPRQuad2,{x_ipProduct=Vivado 2025.2,x_ipVendor=xilinx.com,x_ipLibrary=module_ref,x_ipName=GPRQuad2,x_ipVersion=1.0,x_ipCoreRevision=1,x_ipLanguage=VHDL,x_ipSimLanguage=VHDL}";
  attribute downgradeipidentifiedwarnings : string;
  attribute downgradeipidentifiedwarnings of MainDesign_GPRQuad2_0_0 : entity is "yes";
  attribute ip_definition_source : string;
  attribute ip_definition_source of MainDesign_GPRQuad2_0_0 : entity is "module_ref";
end MainDesign_GPRQuad2_0_0;

architecture stub of MainDesign_GPRQuad2_0_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "clk,readQuadIndex[1:0],writeQuadIndex[1:0],portA_en,portA_regType[1:0],portA_regIdx[2:0],portA_regChan[1:0],portA_readOutData[127:0],portB_en,portB_regType[1:0],portB_regIdx[2:0],portB_regChan[1:0],portB_readOutData[127:0],portW_en,portW_regType[1:0],portW_regIdx[2:0],portW_regChan[1:0],portW_writeInData[127:0],clka_bram0,addra_bram0[8:0],dina_bram0[31:0],ena_bram0,wea_bram0[0:0],clkb_bram0,addrb_bram0[8:0],enb_bram0,doutb_bram0[31:0],clka_bram1,addra_bram1[8:0],dina_bram1[31:0],ena_bram1,wea_bram1[0:0],clkb_bram1,addrb_bram1[8:0],enb_bram1,doutb_bram1[31:0],clka_bram2,addra_bram2[8:0],dina_bram2[31:0],ena_bram2,wea_bram2[0:0],clkb_bram2,addrb_bram2[8:0],enb_bram2,doutb_bram2[31:0],clka_bram3,addra_bram3[8:0],dina_bram3[31:0],ena_bram3,wea_bram3[0:0],clkb_bram3,addrb_bram3[8:0],enb_bram3,doutb_bram3[31:0],clka_bram4,addra_bram4[8:0],dina_bram4[31:0],ena_bram4,wea_bram4[0:0],clkb_bram4,addrb_bram4[8:0],enb_bram4,doutb_bram4[31:0],clka_bram5,addra_bram5[8:0],dina_bram5[31:0],ena_bram5,wea_bram5[0:0],clkb_bram5,addrb_bram5[8:0],enb_bram5,doutb_bram5[31:0],clka_bram6,addra_bram6[8:0],dina_bram6[31:0],ena_bram6,wea_bram6[0:0],clkb_bram6,addrb_bram6[8:0],enb_bram6,doutb_bram6[31:0],clka_bram7,addra_bram7[8:0],dina_bram7[31:0],ena_bram7,wea_bram7[0:0],clkb_bram7,addrb_bram7[8:0],enb_bram7,doutb_bram7[31:0]";
  attribute x_interface_info : string;
  attribute x_interface_info of clk : signal is "xilinx.com:signal:clock:1.0 clk CLK";
  attribute x_interface_mode : string;
  attribute x_interface_mode of clk : signal is "slave clk";
  attribute x_interface_parameter : string;
  attribute x_interface_parameter of clk : signal is "XIL_INTERFACENAME clk, FREQ_HZ 333250000, ASSOCIATED_BUSIF BRAM0W:BRAM0R:BRAM1W:BRAM1R:BRAM2W:BRAM2R:BRAM3W:BRAM3R:BRAM4W:BRAM4R:BRAM5W:BRAM5R:BRAM6W:BRAM6R:BRAM7W:BRAM7R, FREQ_TOLERANCE_HZ 0, PHASE 0.00, CLK_DOMAIN MainDesign_ddr4_0_0_c0_ddr4_ui_clk, INSERT_VIP 0";
  attribute x_interface_info of clka_bram0 : signal is "xilinx.com:interface:bram:1.0 BRAM0W CLK";
  attribute x_interface_mode of clka_bram0 : signal is "master BRAM0W";
  attribute x_interface_parameter of clka_bram0 : signal is "XIL_INTERFACENAME BRAM0W, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addra_bram0 : signal is "xilinx.com:interface:bram:1.0 BRAM0W ADDR";
  attribute x_interface_info of dina_bram0 : signal is "xilinx.com:interface:bram:1.0 BRAM0W DIN";
  attribute x_interface_info of ena_bram0 : signal is "xilinx.com:interface:bram:1.0 BRAM0W EN";
  attribute x_interface_info of wea_bram0 : signal is "xilinx.com:interface:bram:1.0 BRAM0W WE";
  attribute x_interface_info of clkb_bram0 : signal is "xilinx.com:interface:bram:1.0 BRAM0R CLK";
  attribute x_interface_mode of clkb_bram0 : signal is "master BRAM0R";
  attribute x_interface_parameter of clkb_bram0 : signal is "XIL_INTERFACENAME BRAM0R, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addrb_bram0 : signal is "xilinx.com:interface:bram:1.0 BRAM0R ADDR";
  attribute x_interface_info of enb_bram0 : signal is "xilinx.com:interface:bram:1.0 BRAM0R EN";
  attribute x_interface_info of doutb_bram0 : signal is "xilinx.com:interface:bram:1.0 BRAM0R DOUT";
  attribute x_interface_info of clka_bram1 : signal is "xilinx.com:interface:bram:1.0 BRAM1W CLK";
  attribute x_interface_mode of clka_bram1 : signal is "master BRAM1W";
  attribute x_interface_parameter of clka_bram1 : signal is "XIL_INTERFACENAME BRAM1W, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addra_bram1 : signal is "xilinx.com:interface:bram:1.0 BRAM1W ADDR";
  attribute x_interface_info of dina_bram1 : signal is "xilinx.com:interface:bram:1.0 BRAM1W DIN";
  attribute x_interface_info of ena_bram1 : signal is "xilinx.com:interface:bram:1.0 BRAM1W EN";
  attribute x_interface_info of wea_bram1 : signal is "xilinx.com:interface:bram:1.0 BRAM1W WE";
  attribute x_interface_info of clkb_bram1 : signal is "xilinx.com:interface:bram:1.0 BRAM1R CLK";
  attribute x_interface_mode of clkb_bram1 : signal is "master BRAM1R";
  attribute x_interface_parameter of clkb_bram1 : signal is "XIL_INTERFACENAME BRAM1R, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addrb_bram1 : signal is "xilinx.com:interface:bram:1.0 BRAM1R ADDR";
  attribute x_interface_info of enb_bram1 : signal is "xilinx.com:interface:bram:1.0 BRAM1R EN";
  attribute x_interface_info of doutb_bram1 : signal is "xilinx.com:interface:bram:1.0 BRAM1R DOUT";
  attribute x_interface_info of clka_bram2 : signal is "xilinx.com:interface:bram:1.0 BRAM2W CLK";
  attribute x_interface_mode of clka_bram2 : signal is "master BRAM2W";
  attribute x_interface_parameter of clka_bram2 : signal is "XIL_INTERFACENAME BRAM2W, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addra_bram2 : signal is "xilinx.com:interface:bram:1.0 BRAM2W ADDR";
  attribute x_interface_info of dina_bram2 : signal is "xilinx.com:interface:bram:1.0 BRAM2W DIN";
  attribute x_interface_info of ena_bram2 : signal is "xilinx.com:interface:bram:1.0 BRAM2W EN";
  attribute x_interface_info of wea_bram2 : signal is "xilinx.com:interface:bram:1.0 BRAM2W WE";
  attribute x_interface_info of clkb_bram2 : signal is "xilinx.com:interface:bram:1.0 BRAM2R CLK";
  attribute x_interface_mode of clkb_bram2 : signal is "master BRAM2R";
  attribute x_interface_parameter of clkb_bram2 : signal is "XIL_INTERFACENAME BRAM2R, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addrb_bram2 : signal is "xilinx.com:interface:bram:1.0 BRAM2R ADDR";
  attribute x_interface_info of enb_bram2 : signal is "xilinx.com:interface:bram:1.0 BRAM2R EN";
  attribute x_interface_info of doutb_bram2 : signal is "xilinx.com:interface:bram:1.0 BRAM2R DOUT";
  attribute x_interface_info of clka_bram3 : signal is "xilinx.com:interface:bram:1.0 BRAM3W CLK";
  attribute x_interface_mode of clka_bram3 : signal is "master BRAM3W";
  attribute x_interface_parameter of clka_bram3 : signal is "XIL_INTERFACENAME BRAM3W, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addra_bram3 : signal is "xilinx.com:interface:bram:1.0 BRAM3W ADDR";
  attribute x_interface_info of dina_bram3 : signal is "xilinx.com:interface:bram:1.0 BRAM3W DIN";
  attribute x_interface_info of ena_bram3 : signal is "xilinx.com:interface:bram:1.0 BRAM3W EN";
  attribute x_interface_info of wea_bram3 : signal is "xilinx.com:interface:bram:1.0 BRAM3W WE";
  attribute x_interface_info of clkb_bram3 : signal is "xilinx.com:interface:bram:1.0 BRAM3R CLK";
  attribute x_interface_mode of clkb_bram3 : signal is "master BRAM3R";
  attribute x_interface_parameter of clkb_bram3 : signal is "XIL_INTERFACENAME BRAM3R, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addrb_bram3 : signal is "xilinx.com:interface:bram:1.0 BRAM3R ADDR";
  attribute x_interface_info of enb_bram3 : signal is "xilinx.com:interface:bram:1.0 BRAM3R EN";
  attribute x_interface_info of doutb_bram3 : signal is "xilinx.com:interface:bram:1.0 BRAM3R DOUT";
  attribute x_interface_info of clka_bram4 : signal is "xilinx.com:interface:bram:1.0 BRAM4W CLK";
  attribute x_interface_mode of clka_bram4 : signal is "master BRAM4W";
  attribute x_interface_parameter of clka_bram4 : signal is "XIL_INTERFACENAME BRAM4W, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addra_bram4 : signal is "xilinx.com:interface:bram:1.0 BRAM4W ADDR";
  attribute x_interface_info of dina_bram4 : signal is "xilinx.com:interface:bram:1.0 BRAM4W DIN";
  attribute x_interface_info of ena_bram4 : signal is "xilinx.com:interface:bram:1.0 BRAM4W EN";
  attribute x_interface_info of wea_bram4 : signal is "xilinx.com:interface:bram:1.0 BRAM4W WE";
  attribute x_interface_info of clkb_bram4 : signal is "xilinx.com:interface:bram:1.0 BRAM4R CLK";
  attribute x_interface_mode of clkb_bram4 : signal is "master BRAM4R";
  attribute x_interface_parameter of clkb_bram4 : signal is "XIL_INTERFACENAME BRAM4R, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addrb_bram4 : signal is "xilinx.com:interface:bram:1.0 BRAM4R ADDR";
  attribute x_interface_info of enb_bram4 : signal is "xilinx.com:interface:bram:1.0 BRAM4R EN";
  attribute x_interface_info of doutb_bram4 : signal is "xilinx.com:interface:bram:1.0 BRAM4R DOUT";
  attribute x_interface_info of clka_bram5 : signal is "xilinx.com:interface:bram:1.0 BRAM5W CLK";
  attribute x_interface_mode of clka_bram5 : signal is "master BRAM5W";
  attribute x_interface_parameter of clka_bram5 : signal is "XIL_INTERFACENAME BRAM5W, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addra_bram5 : signal is "xilinx.com:interface:bram:1.0 BRAM5W ADDR";
  attribute x_interface_info of dina_bram5 : signal is "xilinx.com:interface:bram:1.0 BRAM5W DIN";
  attribute x_interface_info of ena_bram5 : signal is "xilinx.com:interface:bram:1.0 BRAM5W EN";
  attribute x_interface_info of wea_bram5 : signal is "xilinx.com:interface:bram:1.0 BRAM5W WE";
  attribute x_interface_info of clkb_bram5 : signal is "xilinx.com:interface:bram:1.0 BRAM5R CLK";
  attribute x_interface_mode of clkb_bram5 : signal is "master BRAM5R";
  attribute x_interface_parameter of clkb_bram5 : signal is "XIL_INTERFACENAME BRAM5R, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addrb_bram5 : signal is "xilinx.com:interface:bram:1.0 BRAM5R ADDR";
  attribute x_interface_info of enb_bram5 : signal is "xilinx.com:interface:bram:1.0 BRAM5R EN";
  attribute x_interface_info of doutb_bram5 : signal is "xilinx.com:interface:bram:1.0 BRAM5R DOUT";
  attribute x_interface_info of clka_bram6 : signal is "xilinx.com:interface:bram:1.0 BRAM6W CLK";
  attribute x_interface_mode of clka_bram6 : signal is "master BRAM6W";
  attribute x_interface_parameter of clka_bram6 : signal is "XIL_INTERFACENAME BRAM6W, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addra_bram6 : signal is "xilinx.com:interface:bram:1.0 BRAM6W ADDR";
  attribute x_interface_info of dina_bram6 : signal is "xilinx.com:interface:bram:1.0 BRAM6W DIN";
  attribute x_interface_info of ena_bram6 : signal is "xilinx.com:interface:bram:1.0 BRAM6W EN";
  attribute x_interface_info of wea_bram6 : signal is "xilinx.com:interface:bram:1.0 BRAM6W WE";
  attribute x_interface_info of clkb_bram6 : signal is "xilinx.com:interface:bram:1.0 BRAM6R CLK";
  attribute x_interface_mode of clkb_bram6 : signal is "master BRAM6R";
  attribute x_interface_parameter of clkb_bram6 : signal is "XIL_INTERFACENAME BRAM6R, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addrb_bram6 : signal is "xilinx.com:interface:bram:1.0 BRAM6R ADDR";
  attribute x_interface_info of enb_bram6 : signal is "xilinx.com:interface:bram:1.0 BRAM6R EN";
  attribute x_interface_info of doutb_bram6 : signal is "xilinx.com:interface:bram:1.0 BRAM6R DOUT";
  attribute x_interface_info of clka_bram7 : signal is "xilinx.com:interface:bram:1.0 BRAM7W CLK";
  attribute x_interface_mode of clka_bram7 : signal is "master BRAM7W";
  attribute x_interface_parameter of clka_bram7 : signal is "XIL_INTERFACENAME BRAM7W, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addra_bram7 : signal is "xilinx.com:interface:bram:1.0 BRAM7W ADDR";
  attribute x_interface_info of dina_bram7 : signal is "xilinx.com:interface:bram:1.0 BRAM7W DIN";
  attribute x_interface_info of ena_bram7 : signal is "xilinx.com:interface:bram:1.0 BRAM7W EN";
  attribute x_interface_info of wea_bram7 : signal is "xilinx.com:interface:bram:1.0 BRAM7W WE";
  attribute x_interface_info of clkb_bram7 : signal is "xilinx.com:interface:bram:1.0 BRAM7R CLK";
  attribute x_interface_mode of clkb_bram7 : signal is "master BRAM7R";
  attribute x_interface_parameter of clkb_bram7 : signal is "XIL_INTERFACENAME BRAM7R, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute x_interface_info of addrb_bram7 : signal is "xilinx.com:interface:bram:1.0 BRAM7R ADDR";
  attribute x_interface_info of enb_bram7 : signal is "xilinx.com:interface:bram:1.0 BRAM7R EN";
  attribute x_interface_info of doutb_bram7 : signal is "xilinx.com:interface:bram:1.0 BRAM7R DOUT";
  attribute x_core_info : string;
  attribute x_core_info of stub : architecture is "GPRQuad2,Vivado 2025.2";
begin
end;
