-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.2 (win64) Build 6299465 Fri Nov 14 19:35:11 GMT 2025
-- Date        : Mon Dec  8 18:20:29 2025
-- Host        : Dragon3 running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub
--               c:/Xilinx/MyXilinxProjects/CPUDrivenGPUTest4/CPUDrivenGPUTest4.gen/sources_1/bd/MainDesign/ip/MainDesign_MemoryController_0_0/MainDesign_MemoryController_0_0_stub.vhdl
-- Design      : MainDesign_MemoryController_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcku5p-ffvb676-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity MainDesign_MemoryController_0_0 is
  Port ( 
    M_AXI_ACLK : in STD_LOGIC;
    M_AXI_ARESETN : in STD_LOGIC;
    M_AXI_AWADDR : out STD_LOGIC_VECTOR ( 29 downto 0 );
    M_AXI_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M_AXI_AWVALID : out STD_LOGIC;
    M_AXI_AWREADY : in STD_LOGIC;
    M_AXI_WDATA : out STD_LOGIC_VECTOR ( 255 downto 0 );
    M_AXI_WSTRB : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M_AXI_WVALID : out STD_LOGIC;
    M_AXI_WREADY : in STD_LOGIC;
    M_AXI_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M_AXI_BVALID : in STD_LOGIC;
    M_AXI_BREADY : out STD_LOGIC;
    M_AXI_ARADDR : out STD_LOGIC_VECTOR ( 29 downto 0 );
    M_AXI_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M_AXI_ARVALID : out STD_LOGIC;
    M_AXI_ARREADY : in STD_LOGIC;
    M_AXI_RDATA : in STD_LOGIC_VECTOR ( 255 downto 0 );
    M_AXI_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M_AXI_RVALID : in STD_LOGIC;
    M_AXI_RREADY : out STD_LOGIC;
    M_AXI_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M_AXI_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M_AXI_ARLOCK : out STD_LOGIC;
    M_AXI_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M_AXI_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M_AXI_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M_AXI_AWLOCK : out STD_LOGIC;
    M_AXI_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M_AXI_ARID : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_AWID : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_RID : in STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_RLAST : in STD_LOGIC;
    M_AXI_WLAST : out STD_LOGIC;
    c0_init_calib_complete : in STD_LOGIC;
    ScanoutReadRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 29 downto 0 );
    ScanoutReadRequestsFIFO_empty : in STD_LOGIC;
    ScanoutReadRequestsFIFO_almost_empty : in STD_LOGIC;
    ScanoutReadRequestsFIFO_rd_en : out STD_LOGIC;
    ScanoutReadResponsesFIFO_full : in STD_LOGIC;
    ScanoutReadResponsesFIFO_wr_data : out STD_LOGIC_VECTOR ( 255 downto 0 );
    ScanoutReadResponsesFIFO_wr_en : out STD_LOGIC;
    ZStencilReadRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 29 downto 0 );
    ZStencilReadRequestsFIFO_empty : in STD_LOGIC;
    ZStencilReadRequestsFIFO_almost_empty : in STD_LOGIC;
    ZStencilReadRequestsFIFO_rd_en : out STD_LOGIC;
    ZStencilReadResponsesFIFO_full : in STD_LOGIC;
    ZStencilReadResponsesFIFO_wr_data : out STD_LOGIC_VECTOR ( 255 downto 0 );
    ZStencilReadResponsesFIFO_wr_en : out STD_LOGIC;
    ZStencilWriteRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 293 downto 0 );
    ZStencilWriteRequestsFIFO_empty : in STD_LOGIC;
    ZStencilWriteRequestsFIFO_almost_empty : in STD_LOGIC;
    ZStencilWriteRequestsFIFO_rd_en : out STD_LOGIC;
    CommandProcReadRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 29 downto 0 );
    CommandProcReadRequestsFIFO_empty : in STD_LOGIC;
    CommandProcReadRequestsFIFO_almost_empty : in STD_LOGIC;
    CommandProcReadRequestsFIFO_rd_en : out STD_LOGIC;
    CommandProcReadResponsesFIFO_full : in STD_LOGIC;
    CommandProcReadResponsesFIFO_wr_data : out STD_LOGIC_VECTOR ( 255 downto 0 );
    CommandProcReadResponsesFIFO_wr_en : out STD_LOGIC;
    CommandProcWriteRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 293 downto 0 );
    CommandProcWriteRequestsFIFO_empty : in STD_LOGIC;
    CommandProcWriteRequestsFIFO_almost_empty : in STD_LOGIC;
    CommandProcWriteRequestsFIFO_rd_en : out STD_LOGIC;
    VBCacheReadRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 29 downto 0 );
    VBCacheReadRequestsFIFO_empty : in STD_LOGIC;
    VBCacheReadRequestsFIFO_almost_empty : in STD_LOGIC;
    VBCacheReadRequestsFIFO_rd_en : out STD_LOGIC;
    VBCacheReadResponsesFIFO_full : in STD_LOGIC;
    VBCacheReadResponsesFIFO_wr_data : out STD_LOGIC_VECTOR ( 255 downto 0 );
    VBCacheReadResponsesFIFO_wr_en : out STD_LOGIC;
    IBCacheReadRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 29 downto 0 );
    IBCacheReadRequestsFIFO_empty : in STD_LOGIC;
    IBCacheReadRequestsFIFO_almost_empty : in STD_LOGIC;
    IBCacheReadRequestsFIFO_rd_en : out STD_LOGIC;
    IBCacheReadResponsesFIFO_full : in STD_LOGIC;
    IBCacheReadResponsesFIFO_wr_data : out STD_LOGIC_VECTOR ( 255 downto 0 );
    IBCacheReadResponsesFIFO_wr_en : out STD_LOGIC;
    PacketDMAReadRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 29 downto 0 );
    PacketDMAReadRequestsFIFO_empty : in STD_LOGIC;
    PacketDMAReadRequestsFIFO_almost_empty : in STD_LOGIC;
    PacketDMAReadRequestsFIFO_rd_en : out STD_LOGIC;
    PacketDMAReadResponsesFIFO_full : in STD_LOGIC;
    PacketDMAReadResponsesFIFO_wr_data : out STD_LOGIC_VECTOR ( 255 downto 0 );
    PacketDMAReadResponsesFIFO_wr_en : out STD_LOGIC;
    PacketDMAWriteRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 293 downto 0 );
    PacketDMAWriteRequestsFIFO_empty : in STD_LOGIC;
    PacketDMAWriteRequestsFIFO_almost_empty : in STD_LOGIC;
    PacketDMAWriteRequestsFIFO_rd_en : out STD_LOGIC;
    TexFetchReadRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 29 downto 0 );
    TexFetchReadRequestsFIFO_empty : in STD_LOGIC;
    TexFetchReadRequestsFIFO_almost_empty : in STD_LOGIC;
    TexFetchReadRequestsFIFO_rd_en : out STD_LOGIC;
    TexFetchReadResponsesFIFO_full : in STD_LOGIC;
    TexFetchReadResponsesFIFO_wr_data : out STD_LOGIC_VECTOR ( 255 downto 0 );
    TexFetchReadResponsesFIFO_wr_en : out STD_LOGIC;
    ROPReadRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 29 downto 0 );
    ROPReadRequestsFIFO_empty : in STD_LOGIC;
    ROPReadRequestsFIFO_almost_empty : in STD_LOGIC;
    ROPReadRequestsFIFO_rd_en : out STD_LOGIC;
    ROPReadResponsesFIFO_full : in STD_LOGIC;
    ROPReadResponsesFIFO_wr_data : out STD_LOGIC_VECTOR ( 255 downto 0 );
    ROPReadResponsesFIFO_wr_en : out STD_LOGIC;
    ROPWriteRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 293 downto 0 );
    ROPWriteRequestsFIFO_empty : in STD_LOGIC;
    ROPWriteRequestsFIFO_almost_empty : in STD_LOGIC;
    ROPWriteRequestsFIFO_rd_en : out STD_LOGIC;
    ClearBlockWriteRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 293 downto 0 );
    ClearBlockWriteRequestsFIFO_empty : in STD_LOGIC;
    ClearBlockWriteRequestsFIFO_almost_empty : in STD_LOGIC;
    ClearBlockWriteRequestsFIFO_rd_en : out STD_LOGIC;
    StatsWriteRequestsFIFO_rd_data : in STD_LOGIC_VECTOR ( 293 downto 0 );
    StatsWriteRequestsFIFO_empty : in STD_LOGIC;
    StatsWriteRequestsFIFO_almost_empty : in STD_LOGIC;
    StatsWriteRequestsFIFO_rd_en : out STD_LOGIC;
    CMD_MemoryControllerIsIdle : out STD_LOGIC;
    STAT_MemReadCyclesIdle : out STD_LOGIC_VECTOR ( 31 downto 0 );
    STAT_MemReadCyclesSpentWorking : out STD_LOGIC_VECTOR ( 31 downto 0 );
    STAT_MemWriteCyclesIdle : out STD_LOGIC_VECTOR ( 31 downto 0 );
    STAT_MemWriteCyclesSpentWorking : out STD_LOGIC_VECTOR ( 31 downto 0 );
    STAT_MemReadCountBytesTransferred : out STD_LOGIC_VECTOR ( 31 downto 0 );
    STAT_MemReadCountTransactions : out STD_LOGIC_VECTOR ( 31 downto 0 );
    STAT_MemReadCountNonScanoutBytesTransferred : out STD_LOGIC_VECTOR ( 31 downto 0 );
    STAT_MemReadCountNonScanoutTransactions : out STD_LOGIC_VECTOR ( 31 downto 0 );
    STAT_MemWriteCountBytesTransferred : out STD_LOGIC_VECTOR ( 31 downto 0 );
    STAT_MemWriteCountTransactions : out STD_LOGIC_VECTOR ( 31 downto 0 );
    DBG_ReadControlState : out STD_LOGIC_VECTOR ( 3 downto 0 );
    DBG_WriteControlState : out STD_LOGIC_VECTOR ( 3 downto 0 );
    DBG_ScanoutReadRequests_Empty : out STD_LOGIC;
    DBG_ScanoutReadResponses_Full : out STD_LOGIC;
    DBG_ScanoutReadRequests_rd_en : out STD_LOGIC;
    DBG_LastWriteAddress : out STD_LOGIC_VECTOR ( 29 downto 0 );
    DBG_LastWriteData : out STD_LOGIC_VECTOR ( 255 downto 0 );
    DBG_LastWriteDataDWORDEnables : out STD_LOGIC_VECTOR ( 7 downto 0 );
    DBG_LastWriteMemoryClientIndex : out STD_LOGIC_VECTOR ( 3 downto 0 );
    DBG_LastReadAddress : out STD_LOGIC_VECTOR ( 29 downto 0 );
    DBG_LastReadMemoryClientIndex : out STD_LOGIC_VECTOR ( 3 downto 0 );
    DBG_ReadRequestsEmptyBitmask : out STD_LOGIC_VECTOR ( 7 downto 0 );
    DBG_WriteRequestsEmptyBitmask : out STD_LOGIC_VECTOR ( 5 downto 0 );
    DBG_ReadResponsesFullBitmask : out STD_LOGIC_VECTOR ( 7 downto 0 )
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of MainDesign_MemoryController_0_0 : entity is "MainDesign_MemoryController_0_0,MemoryController,{}";
  attribute core_generation_info : string;
  attribute core_generation_info of MainDesign_MemoryController_0_0 : entity is "MainDesign_MemoryController_0_0,MemoryController,{x_ipProduct=Vivado 2025.2,x_ipVendor=xilinx.com,x_ipLibrary=module_ref,x_ipName=MemoryController,x_ipVersion=1.0,x_ipCoreRevision=1,x_ipLanguage=VHDL,x_ipSimLanguage=VHDL,C_M_START_DATA_VALUE=0x00000000,C_M_TARGET_SLAVE_BASE_ADDR=0x00000000,C_M_AXI_ADDR_WIDTH=30,C_M_AXI_DATA_WIDTH=256}";
  attribute downgradeipidentifiedwarnings : string;
  attribute downgradeipidentifiedwarnings of MainDesign_MemoryController_0_0 : entity is "yes";
  attribute ip_definition_source : string;
  attribute ip_definition_source of MainDesign_MemoryController_0_0 : entity is "module_ref";
end MainDesign_MemoryController_0_0;

architecture stub of MainDesign_MemoryController_0_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "M_AXI_ACLK,M_AXI_ARESETN,M_AXI_AWADDR[29:0],M_AXI_AWPROT[2:0],M_AXI_AWVALID,M_AXI_AWREADY,M_AXI_WDATA[255:0],M_AXI_WSTRB[31:0],M_AXI_WVALID,M_AXI_WREADY,M_AXI_BRESP[1:0],M_AXI_BVALID,M_AXI_BREADY,M_AXI_ARADDR[29:0],M_AXI_ARPROT[2:0],M_AXI_ARVALID,M_AXI_ARREADY,M_AXI_RDATA[255:0],M_AXI_RRESP[1:0],M_AXI_RVALID,M_AXI_RREADY,M_AXI_ARBURST[1:0],M_AXI_ARCACHE[3:0],M_AXI_ARLEN[7:0],M_AXI_ARLOCK,M_AXI_ARSIZE[2:0],M_AXI_AWBURST[1:0],M_AXI_AWCACHE[3:0],M_AXI_AWLEN[7:0],M_AXI_AWLOCK,M_AXI_AWSIZE[2:0],M_AXI_ARID[3:0],M_AXI_AWID[3:0],M_AXI_RID[3:0],M_AXI_RLAST,M_AXI_WLAST,c0_init_calib_complete,ScanoutReadRequestsFIFO_rd_data[29:0],ScanoutReadRequestsFIFO_empty,ScanoutReadRequestsFIFO_almost_empty,ScanoutReadRequestsFIFO_rd_en,ScanoutReadResponsesFIFO_full,ScanoutReadResponsesFIFO_wr_data[255:0],ScanoutReadResponsesFIFO_wr_en,ZStencilReadRequestsFIFO_rd_data[29:0],ZStencilReadRequestsFIFO_empty,ZStencilReadRequestsFIFO_almost_empty,ZStencilReadRequestsFIFO_rd_en,ZStencilReadResponsesFIFO_full,ZStencilReadResponsesFIFO_wr_data[255:0],ZStencilReadResponsesFIFO_wr_en,ZStencilWriteRequestsFIFO_rd_data[293:0],ZStencilWriteRequestsFIFO_empty,ZStencilWriteRequestsFIFO_almost_empty,ZStencilWriteRequestsFIFO_rd_en,CommandProcReadRequestsFIFO_rd_data[29:0],CommandProcReadRequestsFIFO_empty,CommandProcReadRequestsFIFO_almost_empty,CommandProcReadRequestsFIFO_rd_en,CommandProcReadResponsesFIFO_full,CommandProcReadResponsesFIFO_wr_data[255:0],CommandProcReadResponsesFIFO_wr_en,CommandProcWriteRequestsFIFO_rd_data[293:0],CommandProcWriteRequestsFIFO_empty,CommandProcWriteRequestsFIFO_almost_empty,CommandProcWriteRequestsFIFO_rd_en,VBCacheReadRequestsFIFO_rd_data[29:0],VBCacheReadRequestsFIFO_empty,VBCacheReadRequestsFIFO_almost_empty,VBCacheReadRequestsFIFO_rd_en,VBCacheReadResponsesFIFO_full,VBCacheReadResponsesFIFO_wr_data[255:0],VBCacheReadResponsesFIFO_wr_en,IBCacheReadRequestsFIFO_rd_data[29:0],IBCacheReadRequestsFIFO_empty,IBCacheReadRequestsFIFO_almost_empty,IBCacheReadRequestsFIFO_rd_en,IBCacheReadResponsesFIFO_full,IBCacheReadResponsesFIFO_wr_data[255:0],IBCacheReadResponsesFIFO_wr_en,PacketDMAReadRequestsFIFO_rd_data[29:0],PacketDMAReadRequestsFIFO_empty,PacketDMAReadRequestsFIFO_almost_empty,PacketDMAReadRequestsFIFO_rd_en,PacketDMAReadResponsesFIFO_full,PacketDMAReadResponsesFIFO_wr_data[255:0],PacketDMAReadResponsesFIFO_wr_en,PacketDMAWriteRequestsFIFO_rd_data[293:0],PacketDMAWriteRequestsFIFO_empty,PacketDMAWriteRequestsFIFO_almost_empty,PacketDMAWriteRequestsFIFO_rd_en,TexFetchReadRequestsFIFO_rd_data[29:0],TexFetchReadRequestsFIFO_empty,TexFetchReadRequestsFIFO_almost_empty,TexFetchReadRequestsFIFO_rd_en,TexFetchReadResponsesFIFO_full,TexFetchReadResponsesFIFO_wr_data[255:0],TexFetchReadResponsesFIFO_wr_en,ROPReadRequestsFIFO_rd_data[29:0],ROPReadRequestsFIFO_empty,ROPReadRequestsFIFO_almost_empty,ROPReadRequestsFIFO_rd_en,ROPReadResponsesFIFO_full,ROPReadResponsesFIFO_wr_data[255:0],ROPReadResponsesFIFO_wr_en,ROPWriteRequestsFIFO_rd_data[293:0],ROPWriteRequestsFIFO_empty,ROPWriteRequestsFIFO_almost_empty,ROPWriteRequestsFIFO_rd_en,ClearBlockWriteRequestsFIFO_rd_data[293:0],ClearBlockWriteRequestsFIFO_empty,ClearBlockWriteRequestsFIFO_almost_empty,ClearBlockWriteRequestsFIFO_rd_en,StatsWriteRequestsFIFO_rd_data[293:0],StatsWriteRequestsFIFO_empty,StatsWriteRequestsFIFO_almost_empty,StatsWriteRequestsFIFO_rd_en,CMD_MemoryControllerIsIdle,STAT_MemReadCyclesIdle[31:0],STAT_MemReadCyclesSpentWorking[31:0],STAT_MemWriteCyclesIdle[31:0],STAT_MemWriteCyclesSpentWorking[31:0],STAT_MemReadCountBytesTransferred[31:0],STAT_MemReadCountTransactions[31:0],STAT_MemReadCountNonScanoutBytesTransferred[31:0],STAT_MemReadCountNonScanoutTransactions[31:0],STAT_MemWriteCountBytesTransferred[31:0],STAT_MemWriteCountTransactions[31:0],DBG_ReadControlState[3:0],DBG_WriteControlState[3:0],DBG_ScanoutReadRequests_Empty,DBG_ScanoutReadResponses_Full,DBG_ScanoutReadRequests_rd_en,DBG_LastWriteAddress[29:0],DBG_LastWriteData[255:0],DBG_LastWriteDataDWORDEnables[7:0],DBG_LastWriteMemoryClientIndex[3:0],DBG_LastReadAddress[29:0],DBG_LastReadMemoryClientIndex[3:0],DBG_ReadRequestsEmptyBitmask[7:0],DBG_WriteRequestsEmptyBitmask[5:0],DBG_ReadResponsesFullBitmask[7:0]";
  attribute x_interface_info : string;
  attribute x_interface_info of M_AXI_ACLK : signal is "xilinx.com:signal:clock:1.0 M_AXI_ACLK CLK";
  attribute x_interface_mode : string;
  attribute x_interface_mode of M_AXI_ACLK : signal is "slave M_AXI_ACLK";
  attribute x_interface_parameter : string;
  attribute x_interface_parameter of M_AXI_ACLK : signal is "XIL_INTERFACENAME M_AXI_ACLK, ASSOCIATED_BUSIF M_AXI:ScanoutReadRequests:ScanoutReadResponses:ZStencilReadRequests:ZStencilReadResponses:ZStencilWriteRequests:CommandProcReadRequests:CommandProcReadResponses:CommandProcWriteRequests:VBCacheReadRequests:VBCacheReadResponses:IBCacheReadRequests:IBCacheReadResponses:PacketDMAReadRequests:PacketDMAReadResponses:PacketDMAWriteRequests:TexFetchReadRequests:TexFetchReadResponses:ROPReadRequests:ROPReadResponses:ROPWriteRequests:ClearBlockWriteRequests:StatsWriteRequests, ASSOCIATED_RESET M_AXI_ARESETN, FREQ_HZ 333250000, FREQ_TOLERANCE_HZ 0, PHASE 0.00, CLK_DOMAIN MainDesign_ddr4_0_0_c0_ddr4_ui_clk, INSERT_VIP 0";
  attribute x_interface_info of M_AXI_ARESETN : signal is "xilinx.com:signal:reset:1.0 M_AXI_ARESETN RST";
  attribute x_interface_mode of M_AXI_ARESETN : signal is "slave M_AXI_ARESETN";
  attribute x_interface_parameter of M_AXI_ARESETN : signal is "XIL_INTERFACENAME M_AXI_ARESETN, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute x_interface_info of M_AXI_AWADDR : signal is "xilinx.com:interface:aximm:1.0 M_AXI AWADDR";
  attribute x_interface_mode of M_AXI_AWADDR : signal is "master M_AXI";
  attribute x_interface_parameter of M_AXI_AWADDR : signal is "XIL_INTERFACENAME M_AXI, CLK_DOMAIN MainDesign_ddr4_0_0_c0_ddr4_ui_clk, FREQ_HZ 333250000, MAX_BURST_LENGTH 16, NUM_WRITE_OUTSTANDING 32, NUM_READ_OUTSTANDING 32, SUPPORTS_NARROW_BURST 0, READ_WRITE_MODE READ_WRITE, BUSER_WIDTH 0, RUSER_WIDTH 0, WUSER_WIDTH 0, ARUSER_WIDTH 0, AWUSER_WIDTH 0, ADDR_WIDTH 30, ID_WIDTH 4, PROTOCOL AXI4, DATA_WIDTH 256, HAS_BURST 1, HAS_CACHE 1, HAS_LOCK 1, HAS_PROT 1, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.00, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute x_interface_info of M_AXI_AWPROT : signal is "xilinx.com:interface:aximm:1.0 M_AXI AWPROT";
  attribute x_interface_info of M_AXI_AWVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI AWVALID";
  attribute x_interface_info of M_AXI_AWREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI AWREADY";
  attribute x_interface_info of M_AXI_WDATA : signal is "xilinx.com:interface:aximm:1.0 M_AXI WDATA";
  attribute x_interface_info of M_AXI_WSTRB : signal is "xilinx.com:interface:aximm:1.0 M_AXI WSTRB";
  attribute x_interface_info of M_AXI_WVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI WVALID";
  attribute x_interface_info of M_AXI_WREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI WREADY";
  attribute x_interface_info of M_AXI_BRESP : signal is "xilinx.com:interface:aximm:1.0 M_AXI BRESP";
  attribute x_interface_info of M_AXI_BVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI BVALID";
  attribute x_interface_info of M_AXI_BREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI BREADY";
  attribute x_interface_info of M_AXI_ARADDR : signal is "xilinx.com:interface:aximm:1.0 M_AXI ARADDR";
  attribute x_interface_info of M_AXI_ARPROT : signal is "xilinx.com:interface:aximm:1.0 M_AXI ARPROT";
  attribute x_interface_info of M_AXI_ARVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI ARVALID";
  attribute x_interface_info of M_AXI_ARREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI ARREADY";
  attribute x_interface_info of M_AXI_RDATA : signal is "xilinx.com:interface:aximm:1.0 M_AXI RDATA";
  attribute x_interface_info of M_AXI_RRESP : signal is "xilinx.com:interface:aximm:1.0 M_AXI RRESP";
  attribute x_interface_info of M_AXI_RVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI RVALID";
  attribute x_interface_info of M_AXI_RREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI RREADY";
  attribute x_interface_info of M_AXI_ARBURST : signal is "xilinx.com:interface:aximm:1.0 M_AXI ARBURST";
  attribute x_interface_info of M_AXI_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 M_AXI ARCACHE";
  attribute x_interface_info of M_AXI_ARLEN : signal is "xilinx.com:interface:aximm:1.0 M_AXI ARLEN";
  attribute x_interface_info of M_AXI_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 M_AXI ARLOCK";
  attribute x_interface_info of M_AXI_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 M_AXI ARSIZE";
  attribute x_interface_info of M_AXI_AWBURST : signal is "xilinx.com:interface:aximm:1.0 M_AXI AWBURST";
  attribute x_interface_info of M_AXI_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 M_AXI AWCACHE";
  attribute x_interface_info of M_AXI_AWLEN : signal is "xilinx.com:interface:aximm:1.0 M_AXI AWLEN";
  attribute x_interface_info of M_AXI_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 M_AXI AWLOCK";
  attribute x_interface_info of M_AXI_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 M_AXI AWSIZE";
  attribute x_interface_info of M_AXI_ARID : signal is "xilinx.com:interface:aximm:1.0 M_AXI ARID";
  attribute x_interface_info of M_AXI_AWID : signal is "xilinx.com:interface:aximm:1.0 M_AXI AWID";
  attribute x_interface_info of M_AXI_RID : signal is "xilinx.com:interface:aximm:1.0 M_AXI RID";
  attribute x_interface_info of M_AXI_RLAST : signal is "xilinx.com:interface:aximm:1.0 M_AXI RLAST";
  attribute x_interface_info of M_AXI_WLAST : signal is "xilinx.com:interface:aximm:1.0 M_AXI WLAST";
  attribute x_interface_info of ScanoutReadRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 ScanoutReadRequests RD_DATA";
  attribute x_interface_mode of ScanoutReadRequestsFIFO_rd_data : signal is "master ScanoutReadRequests";
  attribute x_interface_info of ScanoutReadRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 ScanoutReadRequests EMPTY";
  attribute x_interface_info of ScanoutReadRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 ScanoutReadRequests ALMOST_EMPTY";
  attribute x_interface_info of ScanoutReadRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 ScanoutReadRequests RD_EN";
  attribute x_interface_info of ScanoutReadResponsesFIFO_full : signal is "xilinx.com:interface:fifo_write:1.0 ScanoutReadResponses FULL";
  attribute x_interface_mode of ScanoutReadResponsesFIFO_full : signal is "master ScanoutReadResponses";
  attribute x_interface_info of ScanoutReadResponsesFIFO_wr_data : signal is "xilinx.com:interface:fifo_write:1.0 ScanoutReadResponses WR_DATA";
  attribute x_interface_info of ScanoutReadResponsesFIFO_wr_en : signal is "xilinx.com:interface:fifo_write:1.0 ScanoutReadResponses WR_EN";
  attribute x_interface_info of ZStencilReadRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 ZStencilReadRequests RD_DATA";
  attribute x_interface_mode of ZStencilReadRequestsFIFO_rd_data : signal is "master ZStencilReadRequests";
  attribute x_interface_info of ZStencilReadRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 ZStencilReadRequests EMPTY";
  attribute x_interface_info of ZStencilReadRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 ZStencilReadRequests ALMOST_EMPTY";
  attribute x_interface_info of ZStencilReadRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 ZStencilReadRequests RD_EN";
  attribute x_interface_info of ZStencilReadResponsesFIFO_full : signal is "xilinx.com:interface:fifo_write:1.0 ZStencilReadResponses FULL";
  attribute x_interface_mode of ZStencilReadResponsesFIFO_full : signal is "master ZStencilReadResponses";
  attribute x_interface_info of ZStencilReadResponsesFIFO_wr_data : signal is "xilinx.com:interface:fifo_write:1.0 ZStencilReadResponses WR_DATA";
  attribute x_interface_info of ZStencilReadResponsesFIFO_wr_en : signal is "xilinx.com:interface:fifo_write:1.0 ZStencilReadResponses WR_EN";
  attribute x_interface_info of ZStencilWriteRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 ZStencilWriteRequests RD_DATA";
  attribute x_interface_mode of ZStencilWriteRequestsFIFO_rd_data : signal is "master ZStencilWriteRequests";
  attribute x_interface_info of ZStencilWriteRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 ZStencilWriteRequests EMPTY";
  attribute x_interface_info of ZStencilWriteRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 ZStencilWriteRequests ALMOST_EMPTY";
  attribute x_interface_info of ZStencilWriteRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 ZStencilWriteRequests RD_EN";
  attribute x_interface_info of CommandProcReadRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 CommandProcReadRequests RD_DATA";
  attribute x_interface_mode of CommandProcReadRequestsFIFO_rd_data : signal is "master CommandProcReadRequests";
  attribute x_interface_info of CommandProcReadRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 CommandProcReadRequests EMPTY";
  attribute x_interface_info of CommandProcReadRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 CommandProcReadRequests ALMOST_EMPTY";
  attribute x_interface_info of CommandProcReadRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 CommandProcReadRequests RD_EN";
  attribute x_interface_info of CommandProcReadResponsesFIFO_full : signal is "xilinx.com:interface:fifo_write:1.0 CommandProcReadResponses FULL";
  attribute x_interface_mode of CommandProcReadResponsesFIFO_full : signal is "master CommandProcReadResponses";
  attribute x_interface_info of CommandProcReadResponsesFIFO_wr_data : signal is "xilinx.com:interface:fifo_write:1.0 CommandProcReadResponses WR_DATA";
  attribute x_interface_info of CommandProcReadResponsesFIFO_wr_en : signal is "xilinx.com:interface:fifo_write:1.0 CommandProcReadResponses WR_EN";
  attribute x_interface_info of CommandProcWriteRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 CommandProcWriteRequests RD_DATA";
  attribute x_interface_mode of CommandProcWriteRequestsFIFO_rd_data : signal is "master CommandProcWriteRequests";
  attribute x_interface_info of CommandProcWriteRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 CommandProcWriteRequests EMPTY";
  attribute x_interface_info of CommandProcWriteRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 CommandProcWriteRequests ALMOST_EMPTY";
  attribute x_interface_info of CommandProcWriteRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 CommandProcWriteRequests RD_EN";
  attribute x_interface_info of VBCacheReadRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 VBCacheReadRequests RD_DATA";
  attribute x_interface_mode of VBCacheReadRequestsFIFO_rd_data : signal is "master VBCacheReadRequests";
  attribute x_interface_info of VBCacheReadRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 VBCacheReadRequests EMPTY";
  attribute x_interface_info of VBCacheReadRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 VBCacheReadRequests ALMOST_EMPTY";
  attribute x_interface_info of VBCacheReadRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 VBCacheReadRequests RD_EN";
  attribute x_interface_info of VBCacheReadResponsesFIFO_full : signal is "xilinx.com:interface:fifo_write:1.0 VBCacheReadResponses FULL";
  attribute x_interface_mode of VBCacheReadResponsesFIFO_full : signal is "master VBCacheReadResponses";
  attribute x_interface_info of VBCacheReadResponsesFIFO_wr_data : signal is "xilinx.com:interface:fifo_write:1.0 VBCacheReadResponses WR_DATA";
  attribute x_interface_info of VBCacheReadResponsesFIFO_wr_en : signal is "xilinx.com:interface:fifo_write:1.0 VBCacheReadResponses WR_EN";
  attribute x_interface_info of IBCacheReadRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 IBCacheReadRequests RD_DATA";
  attribute x_interface_mode of IBCacheReadRequestsFIFO_rd_data : signal is "master IBCacheReadRequests";
  attribute x_interface_info of IBCacheReadRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 IBCacheReadRequests EMPTY";
  attribute x_interface_info of IBCacheReadRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 IBCacheReadRequests ALMOST_EMPTY";
  attribute x_interface_info of IBCacheReadRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 IBCacheReadRequests RD_EN";
  attribute x_interface_info of IBCacheReadResponsesFIFO_full : signal is "xilinx.com:interface:fifo_write:1.0 IBCacheReadResponses FULL";
  attribute x_interface_mode of IBCacheReadResponsesFIFO_full : signal is "master IBCacheReadResponses";
  attribute x_interface_info of IBCacheReadResponsesFIFO_wr_data : signal is "xilinx.com:interface:fifo_write:1.0 IBCacheReadResponses WR_DATA";
  attribute x_interface_info of IBCacheReadResponsesFIFO_wr_en : signal is "xilinx.com:interface:fifo_write:1.0 IBCacheReadResponses WR_EN";
  attribute x_interface_info of PacketDMAReadRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 PacketDMAReadRequests RD_DATA";
  attribute x_interface_mode of PacketDMAReadRequestsFIFO_rd_data : signal is "master PacketDMAReadRequests";
  attribute x_interface_info of PacketDMAReadRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 PacketDMAReadRequests EMPTY";
  attribute x_interface_info of PacketDMAReadRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 PacketDMAReadRequests ALMOST_EMPTY";
  attribute x_interface_info of PacketDMAReadRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 PacketDMAReadRequests RD_EN";
  attribute x_interface_info of PacketDMAReadResponsesFIFO_full : signal is "xilinx.com:interface:fifo_write:1.0 PacketDMAReadResponses FULL";
  attribute x_interface_mode of PacketDMAReadResponsesFIFO_full : signal is "master PacketDMAReadResponses";
  attribute x_interface_info of PacketDMAReadResponsesFIFO_wr_data : signal is "xilinx.com:interface:fifo_write:1.0 PacketDMAReadResponses WR_DATA";
  attribute x_interface_info of PacketDMAReadResponsesFIFO_wr_en : signal is "xilinx.com:interface:fifo_write:1.0 PacketDMAReadResponses WR_EN";
  attribute x_interface_info of PacketDMAWriteRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 PacketDMAWriteRequests RD_DATA";
  attribute x_interface_mode of PacketDMAWriteRequestsFIFO_rd_data : signal is "master PacketDMAWriteRequests";
  attribute x_interface_info of PacketDMAWriteRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 PacketDMAWriteRequests EMPTY";
  attribute x_interface_info of PacketDMAWriteRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 PacketDMAWriteRequests ALMOST_EMPTY";
  attribute x_interface_info of PacketDMAWriteRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 PacketDMAWriteRequests RD_EN";
  attribute x_interface_info of TexFetchReadRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 TexFetchReadRequests RD_DATA";
  attribute x_interface_mode of TexFetchReadRequestsFIFO_rd_data : signal is "master TexFetchReadRequests";
  attribute x_interface_info of TexFetchReadRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 TexFetchReadRequests EMPTY";
  attribute x_interface_info of TexFetchReadRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 TexFetchReadRequests ALMOST_EMPTY";
  attribute x_interface_info of TexFetchReadRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 TexFetchReadRequests RD_EN";
  attribute x_interface_info of TexFetchReadResponsesFIFO_full : signal is "xilinx.com:interface:fifo_write:1.0 TexFetchReadResponses FULL";
  attribute x_interface_mode of TexFetchReadResponsesFIFO_full : signal is "master TexFetchReadResponses";
  attribute x_interface_info of TexFetchReadResponsesFIFO_wr_data : signal is "xilinx.com:interface:fifo_write:1.0 TexFetchReadResponses WR_DATA";
  attribute x_interface_info of TexFetchReadResponsesFIFO_wr_en : signal is "xilinx.com:interface:fifo_write:1.0 TexFetchReadResponses WR_EN";
  attribute x_interface_info of ROPReadRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 ROPReadRequests RD_DATA";
  attribute x_interface_mode of ROPReadRequestsFIFO_rd_data : signal is "master ROPReadRequests";
  attribute x_interface_info of ROPReadRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 ROPReadRequests EMPTY";
  attribute x_interface_info of ROPReadRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 ROPReadRequests ALMOST_EMPTY";
  attribute x_interface_info of ROPReadRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 ROPReadRequests RD_EN";
  attribute x_interface_info of ROPReadResponsesFIFO_full : signal is "xilinx.com:interface:fifo_write:1.0 ROPReadResponses FULL";
  attribute x_interface_mode of ROPReadResponsesFIFO_full : signal is "master ROPReadResponses";
  attribute x_interface_info of ROPReadResponsesFIFO_wr_data : signal is "xilinx.com:interface:fifo_write:1.0 ROPReadResponses WR_DATA";
  attribute x_interface_info of ROPReadResponsesFIFO_wr_en : signal is "xilinx.com:interface:fifo_write:1.0 ROPReadResponses WR_EN";
  attribute x_interface_info of ROPWriteRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 ROPWriteRequests RD_DATA";
  attribute x_interface_mode of ROPWriteRequestsFIFO_rd_data : signal is "master ROPWriteRequests";
  attribute x_interface_info of ROPWriteRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 ROPWriteRequests EMPTY";
  attribute x_interface_info of ROPWriteRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 ROPWriteRequests ALMOST_EMPTY";
  attribute x_interface_info of ROPWriteRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 ROPWriteRequests RD_EN";
  attribute x_interface_info of ClearBlockWriteRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 ClearBlockWriteRequests RD_DATA";
  attribute x_interface_mode of ClearBlockWriteRequestsFIFO_rd_data : signal is "master ClearBlockWriteRequests";
  attribute x_interface_info of ClearBlockWriteRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 ClearBlockWriteRequests EMPTY";
  attribute x_interface_info of ClearBlockWriteRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 ClearBlockWriteRequests ALMOST_EMPTY";
  attribute x_interface_info of ClearBlockWriteRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 ClearBlockWriteRequests RD_EN";
  attribute x_interface_info of StatsWriteRequestsFIFO_rd_data : signal is "xilinx.com:interface:fifo_read:1.0 StatsWriteRequests RD_DATA";
  attribute x_interface_mode of StatsWriteRequestsFIFO_rd_data : signal is "master StatsWriteRequests";
  attribute x_interface_info of StatsWriteRequestsFIFO_empty : signal is "xilinx.com:interface:fifo_read:1.0 StatsWriteRequests EMPTY";
  attribute x_interface_info of StatsWriteRequestsFIFO_almost_empty : signal is "xilinx.com:interface:fifo_read:1.0 StatsWriteRequests ALMOST_EMPTY";
  attribute x_interface_info of StatsWriteRequestsFIFO_rd_en : signal is "xilinx.com:interface:fifo_read:1.0 StatsWriteRequests RD_EN";
  attribute x_core_info : string;
  attribute x_core_info of stub : architecture is "MemoryController,Vivado 2025.2";
begin
end;
